### ISSUE TITLE
First Line Alignment Error

### ISSUE THREAD

**Issue by joeblau** [zipme/RQShineLabel#10]
If you set the UILabel alignment to center or right with multiline text (2+ more lines) the first line is aligned to the left while the rest of the lines are aligned center or right.

**Comment by maxkonovalov** [comment]
Please see this pull request: https://github.com/zipme/RQShineLabel/pull/12

**Comment by joeblau** [comment]
It's fixed! Thanks @maxkonovalov and @zipme
