### ISSUE TITLE
found some bugs with _fadeoutDuration

### ISSUE THREAD

**Issue by zpz1237** [zipme/RQShineLabel#15]
I have tried to change the `_fadeoutDuration` from 2.5s to another value, but it doesn't work
I find that you made mistake in this function,

```
- (void)startAnimationWithDuration:(CFTimeInterval)duration
{
  self.beginTime = CACurrentMediaTime();
  self.endTime = self.beginTime + self.shineDuration;
  self.displaylink.paused = NO;
}
```

Maybe you should add `duration` rather than `self.shineDuration`
I fixed it but another bug happen, and I fixed it finally with inserting these code below into your `updateAttributedString`

```
  if (now > self.endTime) {
    self.displaylink.paused = YES;

      for (NSUInteger i = 0; i < self.attributedString.length; i++) {
          self.characterAnimationDelays[i] = @(arc4random_uniform(self.fadeoutDuration / 2 * 100) / 100.0);
          CGFloat remain = self.fadeoutDuration - [self.characterAnimationDelays[i] floatValue];
          self.characterAnimationDurations[i] = @(arc4random_uniform(remain * 100) / 100.0);
      }

    if (self.completion) {
      self.completion();
    }
```

You use `self.shineDuration` in `setAttributedText`, it will affect the fadeoutAnimation, I add those code to update `characterAnimationDurations` to get the right fadeoutAnimation. Need pull request? Hope you can understand my Chiglish  :）

**Comment by zipme** [comment]
@zpz1237 能否发个PR我看下 😁

**Comment by zpz1237** [comment]
马个鸡... 白扯那么久英文...

**Comment by zpz1237** [comment]
我学一下怎么发PR..

**Comment by warpling** [comment]
Bump! @zipme
